swagger: '2.0'
info:
  description: Testing go-swagger
  title: test-go-swagger
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /test:
    post:
      summary: Create a new animation.
      parameters:
        - name: body
          in: body
          schema:
            type: object
            required:
              - chicken
            default:
              foo: true
              bar: 42
              bam: boom
            properties:
              chicken:
                type: number
              foo: 
                type: boolean
              bar:
                type: integer
              bam:
                type: string
      responses:
        '200':
          description: It works
          schema:
            type: object
            properties:
              message:
                type: string
